In [1]:

import numpy as np # linear algebra
import pandas as pd

In [2]:
movies= pd.read_csv("tmdb_5000_movies.csv")
credits= pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
import ast

In [11]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [12]:
movies.dropna(inplace=True)

In [13]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [17]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [19]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [20]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [21]:
#movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
4667,3060,The Big Parade,The story of an idle rich boy who joins the US...,"[Drama, Romance, War]","[world war i, silent film]","[John Gilbert, Renée Adorée, Hobart Bosworth]",[King Vidor]
1961,290864,Kung Fu Jungle,A martial arts instructor working at a police ...,"[Crime, Action, Thriller]","[martial arts, kung fu, serial killer]","[Donnie Yen, Charlie Yeung, Wang Baoqiang]",[Teddy Chan]
2952,30973,The Visual Bible: The Gospel of John,A word for word depiction of the life of Jesus...,"[Drama, History]","[miracle, jesus christ, last supper, bible, ch...","[Christopher Plummer, Henry Ian Cusick, Stuart...",[Philip Saville]
2542,11778,The Deer Hunter,A group of working-class friends decides to en...,"[Drama, War]","[vietnam veteran, pennsylvania, vietnam, party...","[Robert De Niro, John Cazale, John Savage]",[Michael Cimino]
312,22972,Green Zone,During the U.S.-led occupation of Baghdad in 2...,"[War, Action, Adventure, Drama, Thriller]","[weapon of mass destruction, baghdad, iraqi ]","[Matt Damon, Greg Kinnear, Brendan Gleeson]",[Paul Greengrass]

In [22]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [23]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [25]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [26]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [27]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
#new.head()

In [28]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [30]:
vector = cv.fit_transform(new['tags']).toarray()

In [31]:
vector.shape

(4806, 5000)

In [32]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
# Calculate Distance Between Vectors

In [34]:
# We will use Cosine SImilarity

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity= cosine_similarity(vector)

In [37]:
similarity[0]

array([1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
       0.        ])

In [38]:
sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x: x[1])[1:-6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943),
 (507, 0.2484646732989441),
 (1444, 0.24397501823713333),
 (1920, 0.243599382882345),
 (582, 0.24147264420814754),
 (3730, 0.23904572186687872),
 (74, 0.2267786838055363),
 (3608, 0.2238868314198225),
 (322, 0.22230800575069135),
 (83, 0.22190115272469205),
 (4192, 0.22131333406899523),
 (2333, 0.2173253797873328),
 (1204, 0.21653278478430668),
 (47, 0.2164218276749025),
 (61, 0.21622499104693413),
 (495, 0.2162249910469341),
 (2409, 0.2138089935299395),
 (1537, 0.2125118592516207),
 (942, 0.21251185925162067),
 (972, 0.21251185925162067),
 (466, 0.2114722130550724),
 (1329, 0.21147221305507238),
 (2204, 0.2059714602177749),
 (151, 0.20498001542269692),
 (1201, 0.20283702113484398),
 (973, 0.2),
 (4048, 0.1980534816610477),
 (4405, 0.19518001458970666),
 (1275, 0.19518001458970663),
 (2786, 0.19518001458970663),
 (3162, 0.19518001458970663),
 (2971, 0.19477964490741226),
 (3538, 0.19451950503185494),
 (461, 0.1938916835823703),
 (3327, 0.1938916835823703),
 (305, 0.1932024558334913),
 (36, 0.19194297398747862),
 (931, 0.1916629694999819),
 (150, 0.18869127060994534),
 (220, 0.18832944617230335),
 (27, 0.18752289237539815),
 (2999, 0.18752289237539815),
 (300, 0.18708286933869706),
 (1321, 0.18442777839082936),
 (184, 0.18257418583505539),
 (4, 0.18257418583505536),
 (1071, 0.18257418583505536),
 (301, 0.18182745801939793),
 (373, 0.18018749253911176),
 (67, 0.17928429140015903),
 (46, 0.17654696590094993),
 (7, 0.1763834207376394),
 (2731, 0.17622684421256032),
 (1831, 0.17445567519772937),
 (1344, 0.1739313106957345),
 (149, 0.17313746213992204),
 (2496, 0.17251638983558856),
 (26, 0.17142857142857143),
 (208, 0.1690308509457033),
 (661, 0.1690308509457033),
 (838, 0.1690308509457033),
 (4010, 0.1690308509457033),
 (108, 0.16903085094570328),
 (1808, 0.16673100431301852),
 (94, 0.16574838603294897),
 (2515, 0.16574838603294897),
 (1396, 0.16408253082847338),
 (581, 0.16265001215808886),
 (1297, 0.16239958858823),
 (4336, 0.16239958858823),
 (168, 0.16035674514745463),
 (1383, 0.16035674514745463),
 (31, 0.15971914124998493),
 (91, 0.15971914124998493),
 (3628, 0.15694120514358612),
 (311, 0.1564921592871903),
 (1965, 0.1553638665664663),
 (502, 0.1546617786679401),
 (111, 0.15430334996209188),
 (577, 0.15430334996209188),
 (3354, 0.15430334996209188),
 (158, 0.15289415743128765),
 (1355, 0.15289415743128765),
 (1178, 0.15179418517972906),
 (2169, 0.15179418517972906),
 (172, 0.15118578920369088),
 (490, 0.15118578920369088),
 (17, 0.15026857675938213),
 (1938, 0.14953343588376802),
 (422, 0.14754222271266348),
 (505, 0.14754222271266348),
 (1488, 0.14754222271266348),
 (41, 0.14638501094227999),
 (84, 0.1456438162508838),
 (52, 0.1449427589131121),
 (557, 0.1449427589131121),
 (568, 0.1449427589131121),
 (2686, 0.1449427589131121),
 (56, 0.14414999403128942),
 (249, 0.14414999403128942),
 (2584, 0.14414999403128942),
 (3999, 0.14414999403128942),
 (332, 0.14285714285714285),
 (1220, 0.14285714285714285),
 (1322, 0.14201432049934523),
 (487, 0.14098147537004826),
 (1327, 0.14098147537004826),
 (187, 0.14085904245475275),
 (1945, 0.14085904245475275),
 (2133, 0.14064216928154863),
 (1673, 0.1406421692815486),
 (2480, 0.1406421692815486),
 (4348, 0.1406421692815486),
 (413, 0.1389425035941821),
 (1833, 0.13801311186847084),
 (2620, 0.13801311186847084),
 (2970, 0.13801311186847084),
 (4490, 0.13801311186847084),
 (2873, 0.13801311186847082),
 (1015, 0.13710212427677043),
 (3409, 0.13710212427677043),
 (3622, 0.13710212427677043),
 (342, 0.13662601021279464),
 (127, 0.1357241785076592),
 (595, 0.13533299049019168),
 (1299, 0.13533299049019168),
 (134, 0.13522468075656266),
 (368, 0.13522468075656266),
 (1158, 0.13522468075656266),
 (3675, 0.1336306209562122),
 (1002, 0.13316902848554255),
 (68, 0.13259870882635919),
 (1047, 0.13259870882635919),
 (1096, 0.13259870882635919),
 (1658, 0.13259870882635919),
 (2378, 0.13259870882635919),
 (3376, 0.13259870882635919),
 (740, 0.13199091933711365),
 (1715, 0.1309307341415954),
 (529, 0.13041013273932528),
 (778, 0.13041013273932528),
 (1617, 0.13041013273932528),
 (483, 0.1301200097264711),
 (1747, 0.1301200097264711),
 (420, 0.12888481555661674),
 (1037, 0.12888481555661674),
 (1741, 0.12880163722232754),
 (238, 0.12777531299998796),
 (939, 0.12777531299998796),
 (2713, 0.12741179785940637),
 (3309, 0.12741179785940637),
 (1575, 0.1267731382092775),
 (4203, 0.1267731382092775),
 (228, 0.12598815766974242),
 (432, 0.12598815766974242),
 (3407, 0.12598815766974242),
 (28, 0.12555296411486888),
 (275, 0.12555296411486888),
 (1274, 0.12555296411486888),
 (2075, 0.12555296411486888),
 (2868, 0.12555296411486888),
 (4673, 0.12555296411486888),
 (95, 0.1246111965698067),
 (549, 0.12461119656980668),
 (50, 0.12344267996967351),
 (72, 0.12344267996967351),
 (579, 0.12344267996967351),
 (1982, 0.12344267996967351),
 (454, 0.12327841818038447),
 (2547, 0.12327841818038447),
 (1512, 0.12327841818038446),
 (653, 0.12298800925361816),
 (808, 0.12298800925361816),
 (123, 0.12198750911856666),
 (692, 0.12073632210407378),
 (1277, 0.12073632210407378),
 (1479, 0.12073632210407378),
 (3147, 0.12036162814275589),
 (169, 0.11952286093343936),
 (624, 0.11952286093343936),
 (2259, 0.11952286093343936),
 (3630, 0.11952286093343936),
 (3721, 0.11952286093343936),
 (166, 0.11952286093343935),
 (232, 0.11952286093343935),
 (294, 0.11952286093343935),
 (687, 0.11952286093343935),
 (859, 0.11952286093343935),
 (1616, 0.11952286093343935),
 (1574, 0.1187013882373396),
 (5, 0.1183452670827877),
 (10, 0.11769797726729994),
 (513, 0.11769797726729994),
 (1031, 0.11769797726729994),
 (2583, 0.11769797726729994),
 (3008, 0.11769797726729994),
 (199, 0.11720180773462385),
 (81, 0.11710800875382396),
 (627, 0.11633501014942217),
 (1373, 0.11633501014942217),
 (1727, 0.11633501014942217),
 (2323, 0.11633501014942217),
 (4000, 0.11633501014942217),
 (4018, 0.11633501014942217),
 (87, 0.11595420713048966),
 (126, 0.11595420713048966),
 (508, 0.11595420713048966),
 (777, 0.11501092655705902),
 (14, 0.11428571428571427),
 (854, 0.11428571428571427),
 (900, 0.11428571428571427),
 (1195, 0.11428571428571427),
 (2013, 0.11428571428571427),
 (2450, 0.11428571428571427),
 (3498, 0.11428571428571427),
 (1524, 0.11338934190276817),
 (1721, 0.11338934190276817),
 (2634, 0.11338934190276817),
 (3663, 0.11338934190276817),
 (4135, 0.11338934190276817),
 (141, 0.11338934190276816),
 (1019, 0.1129384878631564),
 (1497, 0.1129384878631564),
 (2439, 0.1129384878631564),
 (131, 0.1126872339638022),
 (330, 0.1126872339638022),
 (1082, 0.1126872339638022),
 (1294, 0.1126872339638022),
 (3340, 0.1126872339638022),
 (3620, 0.1126872339638022),
 (4097, 0.1126872339638022),
 (18, 0.11194341570991125),
 (102, 0.11194341570991125),
 (2106, 0.11194341570991125),
 (2760, 0.11194341570991125),
 (174, 0.11115400287534567),
 (266, 0.11115400287534567),
 (2072, 0.11115400287534567),
 (2181, 0.11115400287534567),
 (239, 0.1109741904046188),
 (3781, 0.11065666703449763),
 (35, 0.11065666703449761),
 (325, 0.11065666703449761),
 (773, 0.11065666703449761),
 (1156, 0.11065666703449761),
 (2521, 0.11065666703449761),
 (3055, 0.11065666703449761),
 (3954, 0.11065666703449761),
 (403, 0.11002971203391539),
 (295, 0.10968169942141635),
 (312, 0.10968169942141635),
 (535, 0.10968169942141635),
 (988, 0.10968169942141635),
 (1273, 0.10968169942141635),
 (3102, 0.10968169942141635),
 (4079, 0.10968169942141635),
 (754, 0.10826639239215334),
 (4230, 0.10826639239215334),
 (139, 0.10821091383745127),
 (4545, 0.10821091383745125),
 (105, 0.10811249552346706),
 (233, 0.10811249552346706),
 (476, 0.10811249552346706),
 (2456, 0.10811249552346706),
 (2762, 0.10811249552346706),
 (3839, 0.10811249552346706),
 (4198, 0.10811249552346706),
 (4623, 0.10811249552346706),
 (182, 0.10690449676496976),
 (334, 0.10690449676496976),
 (643, 0.10690449676496976),
 (898, 0.10690449676496976),
 (1056, 0.10690449676496976),
 (1109, 0.10690449676496976),
 (3783, 0.10690449676496976),
 (85, 0.10631548679075009),
 (33, 0.1057361065275362),
 (148, 0.1057361065275362),
 (157, 0.1057361065275362),
 (263, 0.1057361065275362),
 (715, 0.1057361065275362),
 (935, 0.1057361065275362),
 (1280, 0.1057361065275362),
 (1301, 0.1057361065275362),
 (1501, 0.1057361065275362),
 (2562, 0.1057361065275362),
 (2660, 0.1057361065275362),
 (4331, 0.1057361065275362),
 (129, 0.10559273546969093),
 (510, 0.10559273546969093),
 (1086, 0.10559273546969093),
 (3443, 0.10559273546969093),
 (3464, 0.10559273546969093),
 (4045, 0.10559273546969093),
 (307, 0.10460520656316097),
 (1233, 0.10432810619146021),
 (400, 0.10350983390135313),
 (660, 0.10350983390135313),
 (781, 0.10350983390135313),
 (1942, 0.10350983390135313),
 (2661, 0.10350983390135313),
 (4256, 0.10350983390135313),
 (270, 0.1031078524452934),
 (278, 0.1031078524452934),
 (279, 0.1031078524452934),
 (371, 0.1031078524452934),
 (870, 0.1031078524452934),
 (1202, 0.1031078524452934),
 (1439, 0.1031078524452934),
 (412, 0.1019294382875251),
 (473, 0.1019294382875251),
 (813, 0.1019294382875251),
 (933, 0.1019294382875251),
 (1276, 0.1019294382875251),
 (2003, 0.1019294382875251),
 (2284, 0.1019294382875251),
 (292, 0.10141851056742199),
 (389, 0.10141851056742199),
 (530, 0.10141851056742199),
 (564, 0.10141851056742199),
 (691, 0.10141851056742199),
 (920, 0.10141851056742199),
 (1077, 0.10141851056742199),
 (1408, 0.10141851056742199),
 (2651, 0.10141851056742199),
 (3093, 0.10141851056742199),
 (3736, 0.10141851056742199),
 (410, 0.10079052613579392),
 (1823, 0.10079052613579392),
 (243, 0.09968895725584535),
 (785, 0.09960238411119947),
 (1089, 0.09960238411119947),
 (791, 0.0994490316197694),
 (1474, 0.0994490316197694),
 (1589, 0.0994490316197694),
 (1686, 0.0994490316197694),
 (1756, 0.0994490316197694),
 (2396, 0.0994490316197694),
 (2652, 0.0994490316197694),
 (589, 0.09862273454430757),
 (618, 0.09862273454430757),
 (1357, 0.09862273454430757),
 (2596, 0.09862273454430757),
 (43, 0.09759000729485333),
 (1846, 0.09759000729485333),
 (2488, 0.09759000729485333),
 (2796, 0.09759000729485333),
 (3154, 0.09759000729485333),
 (23, 0.09759000729485331),
 (142, 0.09759000729485331),
 (236, 0.09759000729485331),
 (362, 0.09759000729485331),
 (2093, 0.09759000729485331),
 (160, 0.09694584179118515),
 (206, 0.09694584179118515),
 (596, 0.09658905768325902),
 (1418, 0.09658905768325902),
 (12, 0.09583148474999097),
 (122, 0.09583148474999097),
 (511, 0.09583148474999097),
 (794, 0.09583148474999097),
 (922, 0.09583148474999097),
 (1027, 0.09583148474999097),
 (1306, 0.09583148474999097),
 (2840, 0.09583148474999097),
 (1832, 0.09561828874675149),
 (1924, 0.09561828874675149),
 (479, 0.09508728264112047),
 (1278, 0.09467621366623016),
 (21, 0.09416472308615166),
 (164, 0.09416472308615166),
 (242, 0.09416472308615166),
 (306, 0.09416472308615166),
 (960, 0.09416472308615166),
 (1249, 0.09416472308615166),
 (1523, 0.09416472308615166),
 (2817, 0.09416472308615166),
 (4468, 0.09416472308615166),
 (799, 0.09390602830316849),
 (1496, 0.09376144618769908),
 (2274, 0.09376144618769908),
 (2388, 0.09376144618769908),
 (2856, 0.09376144618769908),
 (4353, 0.09376144618769908),
 (4502, 0.09376144618769908),
 (4516, 0.09376144618769908),
 (4654, 0.09376144618769908),
 (2448, 0.09333167411831966),
 (75, 0.09258200997725513),
 (227, 0.09258200997725513),
 (349, 0.09258200997725513),
 (356, 0.09258200997725513),
 (369, 0.09258200997725513),
 (775, 0.09258200997725513),
 (901, 0.09258200997725513),
 (980, 0.09258200997725513),
 (1004, 0.09258200997725513),
 (1378, 0.09258200997725513),
 (1700, 0.09258200997725513),
 (1790, 0.09258200997725513),
 (3449, 0.09258200997725513),
 (3537, 0.09258200997725513),
 (3816, 0.09258200997725513),
 (4626, 0.09258200997725513),
 (63, 0.09200874124564722),
 (107, 0.09200874124564722),
 (170, 0.09200874124564722),
 (812, 0.09200874124564722),
 (2005, 0.09200874124564722),
 (2968, 0.09200874124564722),
 (32, 0.09116846116771035),
 (45, 0.09116846116771035),
 (363, 0.09116846116771035),
 (467, 0.09116846116771035),
 (491, 0.09116846116771035),
 (2498, 0.09116846116771035),
 (88, 0.09107651110783743),
 (112, 0.09107651110783743),
 (121, 0.09107651110783743),
 (245, 0.09107651110783743),
 (315, 0.09107651110783743),
 (814, 0.09107651110783743),
 (894, 0.09107651110783743),
 (937, 0.09107651110783743),
 (2167, 0.09107651110783743),
 (3301, 0.09107651110783743),
 (222, 0.09035079029052512),
 (381, 0.09035079029052512),
 (2880, 0.09035079029052512),
 (4737, 0.09035079029052512),
 (2386, 0.09009374626955588),
 (1, 0.08964214570007951),
 (96, 0.08964214570007951),
 (241, 0.08964214570007951),
 (547, 0.08964214570007951),
 (1113, 0.08964214570007951),
 (1142, 0.08964214570007951),
 (1269, 0.08964214570007951),
 (2247, 0.08964214570007951),
 (2251, 0.08964214570007951),
 (2304, 0.08964214570007951),
 (2794, 0.08964214570007951),
 (3091, 0.08964214570007951),
 (4259, 0.08964214570007951),
 (4657, 0.08964214570007951),
 (654, 0.089554732567929),
 (1282, 0.089554732567929),
 (103, 0.08877935232369503),
 (230, 0.08877935232369503),
 (1878, 0.08877935232369503),
 (39, 0.08827348295047496),
 (86, 0.08827348295047496),
 (98, 0.08827348295047496),
 (101, 0.08827348295047496),
 (203, 0.08827348295047496),
 (786, 0.08827348295047496),
 (899, 0.08827348295047496),
 (1207, 0.08827348295047496),
 (1473, 0.08827348295047496),
 (3428, 0.08827348295047495),
 (501, 0.0880237696271323),
 (1828, 0.0880237696271323),
 (19, 0.08728715609439694),
 (193, 0.08728715609439694),
 (1139, 0.08728715609439694),
 (1405, 0.08728715609439694),
 (2099, 0.08728715609439694),
 (2250, 0.08728715609439694),
 (2339, 0.08728715609439694),
 (3069, 0.08728715609439694),
 (3218, 0.08728715609439694),
 (3441, 0.08728715609439694),
 (4165, 0.08728715609439694),
 (4492, 0.08728715609439694),
 (4718, 0.08728715609439694),
 (257, 0.08696565534786725),
 (457, 0.08696565534786725),
 (626, 0.08696565534786725),
 (746, 0.08696565534786725),
 (787, 0.08696565534786725),
 (3028, 0.08696565534786725),
 (3140, 0.08696565534786725),
 (3235, 0.08696565534786725),
 (3310, 0.08696565534786725),
 (3423, 0.08696565534786725),
 (153, 0.086568731069961),
 (1898, 0.086568731069961),
 (1534, 0.08656873106996099),
 (51, 0.08586775814821836),
 (1639, 0.08586775814821836),
 (207, 0.0857142857142857),
 (634, 0.0857142857142857),
 (1161, 0.0857142857142857),
 (2253, 0.0857142857142857),
 (2644, 0.0857142857142857),
 (572, 0.08518354199999197),
 (1926, 0.08518354199999197),
 (3431, 0.08518354199999197),
 (37, 0.08451542547285165),
 (472, 0.08451542547285165),
 (534, 0.08451542547285165),
 (680, 0.08451542547285165),
 (776, 0.08451542547285165),
 (885, 0.08451542547285165),
 (987, 0.08451542547285165),
 (1401, 0.08451542547285165),
 (1614, 0.08451542547285165),
 (1621, 0.08451542547285165),
 (1655, 0.08451542547285165),
 (2165, 0.08451542547285165),
 (2203, 0.08451542547285165),
 (2712, 0.08451542547285165),
 (2801, 0.08451542547285165),
 (3389, 0.08451542547285165),
 (3527, 0.08451542547285165),
 (4061, 0.08451542547285165),
 (4431, 0.08451542547285165),
 (4641, 0.08451542547285165),
 (190, 0.08386278693775347),
 (82, 0.08336550215650926),
 (223, 0.08336550215650926),
 (254, 0.08336550215650926),
 (329, 0.08336550215650926),
 (471, 0.08336550215650926),
 (503, 0.08336550215650926),
 (632, 0.08336550215650926),
 (2683, 0.08336550215650926),
 (3355, 0.08336550215650926),
 (3470, 0.08336550215650926),
 (3910, 0.08336550215650926),
 (16, 0.08226127456606226),
 (71, 0.08226127456606226),
 (138, 0.08226127456606226),
 (1560, 0.08226127456606226),
 (1765, 0.08226127456606226),
 (2820, 0.08226127456606226),
 (4055, 0.08226127456606226),
 (4451, 0.08226127456606226),
 (62, 0.08199200616907877),
 (189, 0.08199200616907877),
 (205, 0.08199200616907877),
 (256, 0.08199200616907877),
 (850, 0.08199200616907877),
 (1045, 0.08199200616907877),
 (1323, 0.08199200616907877),
 (1664, 0.08199200616907877),
 (2326, 0.08199200616907877),
 (2763, 0.08199200616907877),
 (2789, 0.08199200616907877),
 (2882, 0.08199200616907877),
 (3155, 0.08199200616907877),
 (3253, 0.08199200616907877),
 (4473, 0.08199200616907877),
 (4568, 0.08199200616907877),
 (11, 0.081199794294115),
 (70, 0.081199794294115),
 (365, 0.081199794294115),
 (1289, 0.081199794294115),
 (1290, 0.081199794294115),
 (1367, 0.081199794294115),
 (2592, 0.081199794294115),
 (3206, 0.081199794294115),
 (3701, 0.081199794294115),
 (274, 0.08058229640253803),
 (59, 0.08024108542850393),
 (587, 0.08017837257372731),
 (737, 0.08017837257372731),
 (2163, 0.08017837257372731),
 (4640, 0.08017837257372731),
 (125, 0.07985957062499247),
 (109, 0.07968190728895957),
 (313, 0.07968190728895957),
 (800, 0.07968190728895957),
 (1288, 0.07968190728895957),
 (1521, 0.07968190728895957),
 (2161, 0.07968190728895957),
 (2317, 0.07968190728895957),
 (2381, 0.07968190728895957),
 (2410, 0.07968190728895957),
 (2551, 0.07968190728895957),
 (2659, 0.07968190728895957),
 (3398, 0.07968190728895957),
 (3430, 0.07968190728895957),
 (3832, 0.07968190728895957),
 (4412, 0.07968190728895957),
 (271, 0.0791945516022682),
 (732, 0.0791945516022682),
 (908, 0.0791945516022682),
 (2395, 0.0791945516022682),
 (2831, 0.0791945516022682),
 (3022, 0.0791945516022682),
 (3907, 0.0791945516022682),
 (229, 0.07913425882489307),
 (76, 0.07824607964359516),
 (79, 0.07824607964359516),
 (543, 0.07824607964359516),
 (591, 0.07824607964359516),
 (784, 0.07824607964359516),
 (979, 0.07824607964359516),
 (1175, 0.07824607964359516),
 (1325, 0.07824607964359516),
 (2021, 0.07824607964359516),
 (2052, 0.07824607964359516),
 (2363, 0.07824607964359516),
 (2701, 0.07824607964359516),
 (2916, 0.07824607964359516),
 (4083, 0.07824607964359516),
 (4123, 0.07824607964359516),
 (2354, 0.07824607964359515),
 (200, 0.07755667343294811),
 (1005, 0.07755667343294811),
 (1348, 0.07755667343294811),
 (1769, 0.07755667343294811),
 (2136, 0.07755667343294811),
 (2212, 0.07755667343294811),
 (3072, 0.07755667343294811),
 (3982, 0.07755667343294811),
 (4006, 0.07755667343294811),
 (9, 0.07733088933397005),
 (536, 0.07733088933397005),
 (674, 0.07733088933397005),
 (1623, 0.07733088933397005),
 (1632, 0.07733088933397005),
 (2241, 0.07733088933397005),
 (3188, 0.07733088933397005),
 (55, 0.07655590023509526),
 (212, 0.07644707871564382),
 (419, 0.07644707871564382),
 (782, 0.07644707871564382),
 (1446, 0.07644707871564382),
 (1883, 0.07644707871564382),
 (2650, 0.07644707871564382),
 (488, 0.07606982611289638),
 (179, 0.07559289460184544),
 (267, 0.07559289460184544),
 (570, 0.07559289460184544),
 (728, 0.07559289460184544),
 (827, 0.07559289460184544),
 (1146, 0.07559289460184544),
 (1168, 0.07559289460184544),
 (1292, 0.07559289460184544),
 (1770, 0.07559289460184544),
 (2533, 0.07559289460184544),
 (2698, 0.07559289460184544),
 (2787, 0.07559289460184544),
 (3390, 0.07559289460184544),
 (3822, 0.07559289460184544),
 (3994, 0.07559289460184544),
 (4099, 0.07559289460184544),
 (4403, 0.07559289460184544),
 (4443, 0.07559289460184544),
 (2056, 0.07476671794188403),
 (97, 0.07476671794188401),
 (262, 0.07476671794188401),
 (635, 0.07476671794188401),
 (665, 0.07476671794188401),
 (997, 0.07476671794188401),
 (1340, 0.07476671794188401),
 (1701, 0.07476671794188401),
 (1996, 0.07476671794188401),
 (183, 0.07466533929465573),
 (215, 0.07396705090823068),
 (704, 0.07396705090823068),
 (752, 0.07396705090823068),
 (1018, 0.07396705090823068),
 (2018, 0.07396705090823068),
 (2320, 0.07396705090823068),
 (4343, 0.07396705090823068),
 (100, 0.07377111135633174),
 (336, 0.07377111135633174),
 (1166, 0.07377111135633174),
 (1262, 0.07377111135633174),
 (1737, 0.07377111135633174),
 (1774, 0.07377111135633174),
 (1990, 0.07377111135633174),
 (2114, 0.07377111135633174),
 (3241, 0.07377111135633174),
 (3671, 0.07377111135633174),
 (3976, 0.07377111135633174),
 (4290, 0.07377111135633174),
 (30, 0.07319250547113999),

In [39]:
def recommend(movie):
    movie_index=new[new['title']== movie].index
    distances = similarity[movie_index]
    movies_list= sorted(list(enumerate(distances[0])), reverse=True, key= lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new.iloc[i[0]].title)

In [40]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [41]:
import pickle

In [42]:
pickle.dump(new,open('movie_list.pkl','wb'))

In [43]:
pickle.dump(new.to_dict(), open("movie_dict.pkl", 'wb'))

In [44]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))